name: medhabit
description: A simple habit tracking and medical notes app.
publish_to: "none" # since it's not a public package

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
  sdk: flutter
  shared_preferences: ^2.2.2

  # UI & Icons
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Local database for notes & habits
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Graphs & charts
  fl_chart: ^0.69.0

  # File & PDF viewing
  file_picker: ^8.0.6
  open_filex: ^4.3.4
  pdfx: ^2.5.0

  # Date & time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
